// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMFqyzC0ap5jsVqvCMLHvLL5NVqKtsrpQ',
    appId: '1:377867190059:web:fba5ff2b9ed71b50918f6e',
    messagingSenderId: '377867190059',
    projectId: 'merit-7fddc',
    authDomain: 'merit-7fddc.firebaseapp.com',
    storageBucket: 'merit-7fddc.appspot.com',
    measurementId: 'G-PGYKV9TPE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAda2VJu8SdrLcw4gXh6Bfs5i9GKeBrwmA',
    appId: '1:377867190059:android:4583e9bd255687f9918f6e',
    messagingSenderId: '377867190059',
    projectId: 'merit-7fddc',
    storageBucket: 'merit-7fddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrdqCQmp5oMEl6gGp0H5kfFm-KN0Pxyjo',
    appId: '1:377867190059:ios:72a2e189e4076ae1918f6e',
    messagingSenderId: '377867190059',
    projectId: 'merit-7fddc',
    storageBucket: 'merit-7fddc.appspot.com',
    iosClientId: '377867190059-kpak6rn5mig64aagjgb7sps1ucrb69mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.meritwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrdqCQmp5oMEl6gGp0H5kfFm-KN0Pxyjo',
    appId: '1:377867190059:ios:72a2e189e4076ae1918f6e',
    messagingSenderId: '377867190059',
    projectId: 'merit-7fddc',
    storageBucket: 'merit-7fddc.appspot.com',
    iosClientId: '377867190059-kpak6rn5mig64aagjgb7sps1ucrb69mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.meritwithfirebase',
  );
}
